name: linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release --target=x86_64-unknown-linux-gnu
    - name: Get Version
      run: echo "VERSION=$(grep -m 1 'version = ' Cargo.toml | cut -d '"' -f 2)" >> $GITHUB_ENV
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: bedrock-up-linux-${{env.VERSION}}
        path: target/x86_64-unknown-linux-gnu/release/bedrock-up
