name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  VERSION: $(grep -m 1 'version = ' Cargo.toml | cut -d '"' -f 2)

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release --target=x86_64-unknown-linux-gnu
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: bedrock-up-linux-${{env.VERSION}}
        path: target/x86_64-unknown-linux-gnu/release/bedrock-up

  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release --target=x86_64-pc-windows-gnu
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: bedrock-up-windows-${{env.VERSION}}
        path: target/x86_64-pc-windows-gnu/release/bedrock-up.exe