name: windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release --target=x86_64-pc-windows-gnu
    - name: Get Version
      run: |
        $version = (Get-Content Cargo.toml | Select-String 'version = ' | Select-Object -First 1).Line -replace '.*version = "([^"]*)".*', '$1'
        echo "VERSION=$version" >> $env:GITHUB_ENV
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: bedrock-up-windows-${{env.VERSION}}
        path: target/x86_64-pc-windows-gnu/release/bedrock-up.exe